name: CI Workflow

on:
  push:
    branches:
      - main  # Specify your trigger branch
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Debug Private Key Length
        run: echo "${{ secrets.VAULT_RSA_KEY }}" | wc -c  # Check the character count
      
      - name: Write RSA Key to File
        env:
          PRIVATE_KEY: ${{ secrets.VAULT_RSA_KEY }}  # Use your synced secret name
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          cat private_key.pem  # Debugging output, remove in production
          openssl rsa -in private_key.pem -check
