name: CI Workflow

on:
  push:
    branches:
      - main  # Specify your trigger branch
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      # Step 1: Debug the private key length and show first 100 characters
      - name: Debug Private Key Length and Content
        run: |
          echo "Private Key Length: ${#PRIVATE_KEY}"  # Print the length of the private key
          echo "First 100 characters of private key:"
          echo "$PRIVATE_KEY" | head -c 100  # Display the first 100 characters of the private key (sanitized)

      # Step 2: Write RSA Key to a file and debug
      - name: Write RSA Key to File
        env:
          PRIVATE_KEY: ${{ secrets.VAULT_RSA_KEY }}  # Use your synced secret name
        run: |
          echo "Writing the private key to private_key.pem..."
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Debugging: Show sanitized contents of private_key.pem (first 100 characters)
          echo "Sanitized contents of private_key.pem (first 100 characters):"
          head -c 100 private_key.pem  # Show first 100 characters of the file

          # Debugging: Show the first 10 lines of the private key (in case of extra newlines or issues)
          echo "First 10 lines of private_key.pem:"
          head -n 10 private_key.pem  # Show the first 10 lines

          # Step 3: Run OpenSSL to validate the private key and capture any error messages
          echo "Running OpenSSL to validate the private key..."
          openssl rsa -in private_key.pem -check || echo "OpenSSL failed to read the private key. Please check the formatting."

      # Optional Step: Display errors or logs for further insight
      - name: Display Logs (If Needed)
        run: |
          echo "Checking the error output in the workflow logs..."
          tail -n 20 /tmp/github-actions-debug.log  # Display the last 20 lines of log (adjust if needed)
