name: CI Workflow

on:
  push:
    branches:
      - main  # Specify your trigger branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Write RSA Key to File
        env:
          PRIVATE_KEY: ${{ secrets.VAULT_RSA_KEY }}  # Use your synced secret name
        run: |
          echo "$PRIVATE_KEY" > private_key.pem  # Corrected to use PRIVATE_KEY
          chmod 600 private_key.pem
          # Add your command that uses the private key here
          openssl rsa -in private_key.pem -check
